# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "99e965342bf7efd76e2e083e857efd2f"
name = "radar-wishlist-app"
handle = "radar-wishlist-app"
application_url = "https://baghdad-none-meant-pixels.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "boyd-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://baghdad-none-meant-pixels.trycloudflare.com/auth/callback",
  "https://baghdad-none-meant-pixels.trycloudflare.com/auth/shopify/callback",
  "https://baghdad-none-meant-pixels.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
